### PR TITLE
documentation functions

### PR DESCRIPTION
**Pull request by scottnath**
@sergesemashko @beynya 

I've added gulp tasks to create docs and push those docs to gh-pages. You can see an example here:
http://scottnath.github.io/pattern-library-utilities/index.html

please let me know what changes you'd like to see.

### CODE REVIEW

**Comment by beynya** [comment]
looks good
@sergesemashko any thoughts?

**Comment by scottnath** [comment]
@sergesemashko @beynya @conortm @rebmullin @e2tha-e 

Hey team,

Not sure who's working on testing out angular, but you can use this gulp task to convert html/twig templates into angular templates, which are javascript. It concatenates all of them into a single file to reduce external-template loading.

Have a great weekend, I'll be out until Monday.

**Comment by scottnath** [comment]
@ericduran @conortm @sergesemashko @beynya @rebmullin @gvorbeck

pull request from last wednesday

**Comment by sergesemashko** [comment]
looks good

**Comment by scottnath** [comment]
cool. will merge

**Pull request merged**
